// <auto-generated />
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216194154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.kasutaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("kasutajanimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parool")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToKasutaja");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.koostisosa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nimetus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("kogus")
                        .HasColumnType("real");

                    b.Property<float>("summa")
                        .HasColumnType("real");

                    b.Property<string>("ühik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ühikuhind")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ToKoostisosa");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.logikande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("kasutaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kirjeldus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kuupäev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToLogiKande");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.maitsmistelogikande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("hinne")
                        .HasColumnType("real");

                    b.Property<string>("kasutaja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kuupäev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("selgitus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToMaitsmistelogikande");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.õllepruulimine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("kirjeldus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kokkuvõtte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("koostisosad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maitsemislogi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("partiikood")
                        .HasColumnType("int");

                    b.Property<string>("partiikuupäev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToÕllepruulimine");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.õllesort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("kirjeldus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("õllepruuliminejaproovipartiid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToÕllesort");
                });
#pragma warning restore 612, 618
        }
    }
}
